# This is the main configuration file for Paper.
# As you can see, there's tons to configure. Some options may impact gameplay, so use
# with caution, and make sure you know what each option does before configuring.
#
# If you need help with the configuration or have any questions related to Paper,
# join us in our Discord or IRC channel.
#
# Discord: https://discord.gg/papermc
# IRC: #paper @ irc.esper.net ( https://webchat.esper.net/?channels=paper ) 
# Website: https://papermc.io/ 
# Docs: https://docs.papermc.io/ 

verbose: false
messages:
  kick:
    authentication-servers-down: There is a temporary network outage at Mojang's end!
    connection-throttle: Connection throttled! Please wait before reconnecting.
    flying-player: Flying is not enabled on this server
    flying-vehicle: Flying is not enabled on this server
  no-permission: '&cI''m sorry, but you do not have permission to perform this command.
    Please contact the server administrators if you believe that this is in error.'
timings:
  really-enabled: false
  enabled: false
  verbose: true
  url: https://timings.aikar.co/
  server-name-privacy: false
  hidden-config-entries:
  - database
  - settings.bungeecord-addresses
  - settings.velocity-support.secret
  - settings.seed
  history-interval: 300
  history-length: 3600
  server-name: Unknown Server
config-version: 27
settings:
  max-joins-per-tick: 3
  track-plugin-scoreboards: false
  fix-entity-position-desync: true
  use-display-name-in-quit-message: false
  load-permissions-yml-before-plugins: true
  region-file-cache-size: 256
  enable-player-collisions: true
  save-empty-scoreboard-teams: false
  bungee-online-mode: true
  incoming-packet-spam-threshold: 300
  use-alternative-luck-formula: false
  velocity-support:
    enabled: false
    online-mode: false
    secret: ''
  console-has-all-permissions: false
  player-auto-save-rate: -1
  max-player-auto-save-per-tick: -1
  fix-target-selector-tag-completion: true
  lag-compensate-block-breaking: true
  send-full-pos-for-hard-colliding-entities: true
  time-command-affects-all-worlds: false
  use-dimension-type-for-custom-spawners: false
  proxy-protocol: false
  resolve-selectors-in-books: false
  log-player-ip-addresses: true
  console:
    enable-brigadier-highlighting: true
    enable-brigadier-completions: true
  suggest-player-names-when-null-tab-completions: true
  watchdog:
    early-warning-every: 5000
    early-warning-delay: 10000
  spam-limiter:
    tab-spam-increment: 1
    tab-spam-limit: 500
    recipe-spam-increment: 1
    recipe-spam-limit: 20
  book-size:
    page-max: 2560
    total-multiplier: 0.98
  loggers:
    deobfuscate-stacktraces: true
    use-rgb-for-named-text-colors: true
  item-validation:
    display-name: 8192
    loc-name: 8192
    lore-line: 8192
    book:
      title: 8192
      author: 8192
      page: 16384
  chunk-loading:
    min-load-radius: 2
    max-concurrent-sends: 2
    autoconfig-send-distance: true
    target-player-chunk-send-rate: 100.0
    global-max-chunk-send-rate: -1.0
    enable-frustum-priority: false
    global-max-chunk-load-rate: -1.0
    player-max-concurrent-loads: 20.0
    global-max-concurrent-loads: 500.0
    player-max-chunk-load-rate: -1.0
  async-chunks:
    threads: -1
  unsupported-settings:
    allow-permanent-block-break-exploits: false
    allow-piston-duplication: false
    perform-username-validation: true
    allow-headless-pistons: false
    allow-permanent-block-break-exploits-readme: This setting controls if players
      should be able to break bedrock, end portals and other intended to be permanent
      blocks.
    allow-piston-duplication-readme: This setting controls if player should be able
      to use TNT duplication, but this also allows duplicating carpet, rails and potentially
      other items
    allow-headless-pistons-readme: This setting controls if players should be able
      to create headless pistons.
  packet-limiter:
    kick-message: '&cSent too many packets'
    limits:
      all:
        interval: 7.0
        max-packet-rate: 500.0
      PacketPlayInAutoRecipe:
        interval: 4.0
        max-packet-rate: 5.0
        action: DROP
world-settings:
  default:
    delay-chunk-unloads-by: 10s
    disable-teleportation-suffocation-check: false
    wandering-trader:
      spawn-minute-length: 1200
      spawn-day-length: 24000
      spawn-chance-failure-increment: 25
      spawn-chance-min: 25
      spawn-chance-max: 75
    game-mechanics:
      fix-curing-zombie-villager-discount-exploit: true
      scan-for-legacy-ender-dragon: true
      disable-pillager-patrols: false
      pillager-patrols:
        spawn-chance: 0.2
        spawn-delay:
          per-player: false
          ticks: 12000
        start:
          per-player: false
          day: 5
      disable-player-crits: false
      disable-sprint-interruption-on-attack: false
      shield-blocking-delay: 5
      disable-end-credits: false
      nerf-pigmen-from-nether-portals: false
      disable-unloaded-chunk-enderpearl-exploit: true
      disable-relative-projectile-velocity: false
      disable-chest-cat-detection: false
      disable-mob-spawner-spawn-egg-transformation: false
    door-breaking-difficulty:
      zombie:
      - HARD
      zombie_villager:
      - HARD
      husk:
      - HARD
      zombified_piglin:
      - HARD
      vindicator:
      - NORMAL
      - HARD
    max-growth-height:
      cactus: 3
      reeds: 3
      bamboo:
        max: 16
        min: 11
    fishing-time-range:
      MinimumTicks: 100
      MaximumTicks: 600
    despawn-ranges:
      monster:
        soft: 32
        hard: 128
      creature:
        soft: 32
        hard: 128
      ambient:
        soft: 32
        hard: 128
      axolotls:
        soft: 32
        hard: 128
      underground_water_creature:
        soft: 32
        hard: 128
      water_creature:
        soft: 32
        hard: 128
      water_ambient:
        soft: 32
        hard: 64
      misc:
        soft: 32
        hard: 128
    falling-block-height-nerf: 0
    tnt-entity-height-nerf: 0
    slime-spawn-height:
      swamp-biome:
        maximum: 70.0
        minimum: 50.0
      slime-chunk:
        maximum: 40.0
    piglins-guard-chests: true
    should-remove-dragon: false
    max-auto-save-chunks-per-tick: 8
    baby-zombie-movement-modifier: 0.5
    optimize-explosions: true
    use-vanilla-world-scoreboard-name-coloring: false
    prevent-moving-into-unloaded-chunks: true
    count-all-mobs-for-spawning: false
    spawn-limits:
      monster: -1
      creature: -1
      ambient: -1
      axolotls: -1
      underground_water_creature: -1
      water_creature: -1
      water_ambient: -1
    ender-dragons-death-always-places-dragon-egg: false
    experience-merge-max-value: -1
    allow-using-signs-inside-spawn-protection: false
    frosted-ice:
      enabled: true
      delay:
        min: 20
        max: 40
    lootables:
      auto-replenish: false
      restrict-player-reloot: true
      reset-seed-on-fill: true
      max-refills: -1
      refresh-min: 12h
      refresh-max: 2d
    filter-nbt-data-from-spawn-eggs-and-related: true
    enable-treasure-maps: false
    treasure-maps-find-already-discovered:
      villager-trade: false
      loot-tables: default
    max-entity-collisions: 0
    disable-creeper-lingering-effect: false
    duplicate-uuid-resolver: saferegen
    duplicate-uuid-saferegen-delete-range: 32
    hopper:
      cooldown-when-full: true
      disable-move-event: false
      ignore-occluding-blocks: true
    mob-effects:
      undead-immune-to-certain-effects: true
      spiders-immune-to-poison-effect: true
      immune-to-wither-effect:
        wither: true
        wither-skeleton: true
    phantoms-do-not-spawn-on-creative-players: true
    phantoms-only-attack-insomniacs: true
    mobs-can-always-pick-up-loot:
      zombies: false
      skeletons: false
    map-item-frame-cursor-update-interval: 10
    allow-player-cramming-damage: false
    anticheat:
      obfuscation:
        items:
          hide-itemmeta: false
          hide-durability: false
    monster-spawn-max-light-level: -1
    allow-non-player-entities-on-scoreboards: false
    portal-search-radius: 128
    portal-create-radius: 16
    portal-search-vanilla-dimension-scaling: true
    keep-spawn-loaded-range: 10
    fix-items-merging-through-walls: false
    keep-spawn-loaded: true
    anti-xray:
      enabled: true
      engine-mode: 1
      max-block-height: 64
      update-radius: 2
      lava-obscures: false
      use-permission: false
      hidden-blocks:
      - copper_ore
      - deepslate_copper_ore
      - gold_ore
      - deepslate_gold_ore
      - iron_ore
      - deepslate_iron_ore
      - coal_ore
      - deepslate_coal_ore
      - lapis_ore
      - deepslate_lapis_ore
      - mossy_cobblestone
      - obsidian
      - chest
      - diamond_ore
      - deepslate_diamond_ore
      - redstone_ore
      - deepslate_redstone_ore
      - clay
      - emerald_ore
      - deepslate_emerald_ore
      - ender_chest
      replacement-blocks:
      - stone
      - oak_planks
      - dirt
    parrots-are-unaffected-by-player-movement: false
    disable-explosion-knockback: false
    nether-ceiling-void-damage-height: 127
    only-players-collide: true
    allow-vehicle-collisions: true
    armor-stands-do-collision-entity-lookups: false
    disable-thunder: false
    skeleton-horse-thunder-spawn-chance: 0.01
    disable-ice-and-snow: false
    fix-climbing-bypassing-cramming-rule: true
    container-update-tick-rate: 1
    prevent-tnt-from-moving-in-water: false
    fixed-chunk-inhabited-time: -1
    water-over-lava-flow-speed: 5
    grass-spread-tick-rate: 4
    redstone-implementation: alternate-current
    iron-golems-can-spawn-in-air: false
    max-leash-distance: 10.0
    show-sign-click-command-failure-msgs-to-player: false
    armor-stands-tick: false
    non-player-arrow-despawn-rate: 20
    creative-arrow-despawn-rate: 20
    spawner-nerfed-mobs-should-jump: false
    entities-target-with-follow-range: false
    wateranimal-spawn-height:
      maximum: default
      minimum: default
    zombies-target-turtle-eggs: true
    unsupported-settings:
      fix-invulnerable-end-crystal-exploit: true
    zombie-villager-infection-chance: -1.0
    all-chunks-are-slime-chunks: false
    mob-spawner-tick-rate: 2
    map-item-frame-cursor-limit: 128
    light-queue-size: 20
    auto-save-interval: -1
    per-player-mob-spawns: true
    generator-settings:
      flat-bedrock: false
    update-pathfinding-on-block-update: false
    split-overstacked-loot: true
    entity-per-chunk-save-limit:
      experience_orb: -1
      snowball: -1
      ender_pearl: -1
      arrow: -1
      fireball: -1
      small_fireball: -1
      area_effect_cloud: 8
      dragon_fireball: 3
      egg: 8
      experience_bottle: 3
      eye_of_ender: 8
      firework_rocket: 8
      llama_spit: 3
      potion: 8
      shulker_bullet: 8
      spectral_arrow: 16
      trident: 16
      wither_skull: 4
    tick-rates:
      sensor:
        villager:
          secondarypoisensor: 40
      behavior:
        villager:
          validatenearbypoi: -1
    feature-seeds:
      generate-random-seeds-for-all: false
    alt-item-despawn-rate:
      enabled: true
      items:
        cobblestone: 300
        netherrack: 300
        sand: 300
        red_sand: 300
        gravel: 300
        dirt: 300
        grass: 300
        pumpkin: 300
        melon_slice: 300
        kelp: 300
        bamboo: 300
        sugar_cane: 300
        twisting_vines: 300
        weeping_vines: 300
        oak_leaves: 300
        spruce_leaves: 300
        birch_leaves: 300
        jungle_leaves: 300
        acacia_leaves: 300
        dark_oak_leaves: 300
        mangrove_leaves: 300
        cactus: 300
        diorite: 300
        granite: 300
        andesite: 300
        scaffolding: 600
